-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."auth" add column "refresh_token_expires_at" timestamptz
--  null;
